<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsTestProject>true</IsTestProject><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <ProjectReference Include="../../src/PurrfectSeat.Api/PurrfectSeat.Api.csproj" />
    <ProjectReference Include="../../src/PurrfectSeat.Infrastructure/PurrfectSeat.Infrastructure.csproj" />
  </ItemGroup>
</Project>
