<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../PurrfectSeat.Domain/PurrfectSeat.Domain.csproj" />
    <ProjectReference Include="../PurrfectSeat.Application/PurrfectSeat.Application.csproj" />
    <ProjectReference Include="../PurrfectSeat.Contracts/PurrfectSeat.Contracts.csproj" />
  </ItemGroup>
</Project>
