<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../src/NetCats.Core/NetCats.Core.csproj" />
    <ProjectReference Include="../../src/NetCats.Generators/NetCats.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
