using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace NetCats.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class KindGenerator : IIncrementalGenerator
{
    private const string AttributeName = "NetCats.Core.GenerateKindAttribute";

    private static readonly DiagnosticDescriptor UnsupportedArity = new(
        "NCGEN001", "Unsupported type-constructor arity", "Type '{0}' has arity {1}; only unary and binary constructors are supported",
        "NetCats.Generation", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor InvalidValueParameter = new(
        "NCGEN002", "Invalid value parameter position", "ValueParameter {0} is invalid for '{1}'",
        "NetCats.Generation", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor MissingPartial = new(
        "NCGEN004", "Kind carrier must be partial", "Type '{0}' must be declared partial",
        "NetCats.Generation", DiagnosticSeverity.Error, true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
                AttributeName,
                static (node, _) => node is TypeDeclarationSyntax,
                static (attributeContext, _) => CreateSpec(attributeContext))
            .Where(static spec => spec is not null)
            .Select(static (spec, _) => spec!);
        context.RegisterSourceOutput(candidates, static (productionContext, spec) => Emit(productionContext, spec));
    }

    private static Spec? CreateSpec(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol type)
        {
            return null;
        }

        var attribute = context.Attributes[0];
        var witness = attribute.ConstructorArguments.Length == 1 && attribute.ConstructorArguments[0].Value is string name
            ? name
            : type.Name + "K";
        var position = attribute.NamedArguments.FirstOrDefault(static pair => pair.Key == "ValueParameter").Value.Value as int? ?? 0;
        var syntax = (TypeDeclarationSyntax)context.TargetNode;
        var location = syntax.AttributeLists.SelectMany(static list => list.Attributes).First().GetLocation();
        return new Spec(
            type.ContainingNamespace.IsGlobalNamespace ? string.Empty : type.ContainingNamespace.ToDisplayString(),
            type.Name,
            witness,
            type.TypeParameters.Select(static parameter => parameter.Name).ToImmutableArray(),
            position,
            syntax.Modifiers.Any(static modifier => modifier.IsKind(SyntaxKind.PartialKeyword)),
            location);
    }

    private static void Emit(SourceProductionContext context, Spec spec)
    {
        if (spec.Arity is < 1 or > 2)
        {
            context.ReportDiagnostic(Diagnostic.Create(UnsupportedArity, spec.Location, spec.TypeName, spec.Arity));
            return;
        }

        if (spec.ValueParameter < 0 || spec.ValueParameter >= spec.Arity)
        {
            context.ReportDiagnostic(Diagnostic.Create(InvalidValueParameter, spec.Location, spec.ValueParameter, spec.TypeName));
            return;
        }

        if (!spec.IsPartial)
        {
            context.ReportDiagnostic(Diagnostic.Create(MissingPartial, spec.Location, spec.TypeName));
            return;
        }

        var fixedParameters = spec.TypeParameters.Where((_, index) => index != spec.ValueParameter).ToArray();
        var fixedList = string.Join(", ", fixedParameters);
        var witness = fixedParameters.Length == 0 ? spec.Witness : spec.Witness + "<" + fixedList + ">";
        var genericPrefix = fixedParameters.Length == 0 ? string.Empty : fixedList + ", ";
        var carrierA = Carrier(spec, "A");
        var carrierB = Carrier(spec, "B");
        var nsOpen = string.IsNullOrEmpty(spec.Namespace) ? string.Empty : "namespace " + spec.Namespace + "\n{\n";
        var nsClose = string.IsNullOrEmpty(spec.Namespace) ? string.Empty : "}\n";
        var source = "// <auto-generated/>\n#nullable enable\n" + nsOpen +
            "public sealed class " + witness + " { private " + spec.Witness + "() { } }\n\n" +
            "public static class " + spec.Witness + "Extensions\n{\n" +
            "    public static global::NetCats.Core.K<" + witness + ", A> ToKind<" + genericPrefix + "A>(this " + carrierA + " source) => new(source);\n" +
            "    public static " + carrierA + " FromKind<" + genericPrefix + "A>(this global::NetCats.Core.K<" + witness + ", A> source) => source.Get<" + carrierA + ">();\n" +
            "    public static " + carrierB + " Map<" + genericPrefix + "A, B>(this " + carrierA + " source, global::System.Func<A, B> selector) => new " + carrierB + "(selector(source.Value));\n" +
            "    public static " + carrierB + " Bind<" + genericPrefix + "A, B>(this " + carrierA + " source, global::System.Func<A, " + carrierB + "> selector) => selector(source.Value);\n" +
            "}\n" + nsClose;
        context.AddSource(spec.TypeName + "." + spec.Witness + ".g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static string Carrier(Spec spec, string valueType)
    {
        var arguments = spec.TypeParameters.Select((parameter, index) => index == spec.ValueParameter ? valueType : parameter);
        var prefix = string.IsNullOrEmpty(spec.Namespace) ? "global::" : "global::" + spec.Namespace + ".";
        return prefix + spec.TypeName + "<" + string.Join(", ", arguments) + ">";
    }

    private sealed class Spec
    {
        public Spec(string @namespace, string typeName, string witness, ImmutableArray<string> typeParameters, int valueParameter, bool isPartial, Location location)
        {
            Namespace = @namespace;
            TypeName = typeName;
            Witness = witness;
            TypeParameters = typeParameters;
            ValueParameter = valueParameter;
            IsPartial = isPartial;
            Location = location;
        }

        public string Namespace { get; }
        public string TypeName { get; }
        public string Witness { get; }
        public ImmutableArray<string> TypeParameters { get; }
        public int ValueParameter { get; }
        public bool IsPartial { get; }
        public Location Location { get; }
        public int Arity => TypeParameters.Length;
    }
}
